### ISSUE TITLE
Интерфейс приложения

### ISSUE THREAD

**Issue by truenorthpaul** [TIN2539/TitleCapitalizationTool#1]
Интерфейс приложения не соответствует требованиям.

**Comment by TIN2539** [comment]
Можно подробней, что не так?

**Comment by truenorthpaul** [comment]
Выводимые строки не соответствуют тем, что указаны в задании:
Enter title to capitalize:
Capitalized title:
Original title:

**Comment by TIN2539** [comment]
В задании такого нету...
![default](https://user-images.githubusercontent.com/37197421/38145222-f568f34e-3450-11e8-8ba4-e0172a0122ed.PNG)

**Comment by truenorthpaul** [comment]
Я показывал обновленное задание на паре, и загрузил его на mystat.
[Задание.docx](https://github.com/TIN2539/TitleCapitalizationTool/files/1864224/default.docx)
