### ISSUE TITLE
Согласование названий фундаметальных типов

### ISSUE THREAD

**Issue by truenorthpaul** [TIN2539/TitleCapitalizationTool#4]
Необходимо согласование в использовании имен для всех фундаментальных типов. Либо везде применять ключевые слова языка C# (int, string. bool и т.д.) или названия платформы .NET Framework (Int32, String, Boolean и т.д.).

**Comment by TIN2539** [comment]
В коде везде используются ключевые слова языка С#

**Comment by truenorthpaul** [comment]
Строка 38: `userString = String.Join(" ", words);`
Строка 122: `userString = String.Join(" ", words);`
